const data = [
  {
    id: "1",
    question:
      "Anaerobiosis leads to lactate formation in muscle due to which one of the following?",
    incorrectAnswers: [
      "Inhibiting hexokinase by glucose-6-phosphate",
      "Providing 2,3-bisphosphoglycerate for the phos- phoglyceromutase reaction",
      "Inhibiting pyruvate kinase by pyruvate",
      "Inhibiting phosphofructokinase-1 by AMP",
    ],
    correctAnswer:
      "Providing substrate for glyceraldehyde- 3-phosphate dehydrogenase. ",
    explanation:
      "Under anaerobic condi- tions, the NADH generated by the glyceraldehyde-3- phosphate dehydrogenase step accumulates. Normally, the NADH would transfer its electrons to mitochondrial NAD+ , and the electrons would be donated to the elec- tron transfer chain. However, in the absence of oxygen",
    image: "",
  },
];

export default data;
